api:
  version: "v1"

https:  
  listener:
    host: "0.0.0.0"
    port: "8082"
    path: "api/${api.version}/*"
  requester:
    sa:  
      accounts:
        host: "mule-worker-internal-rdg-railcards-accounts-sa-v1-sit.uk-e1.cloudhub.io"
        port: "8092"
        basepath: "/api/v1"
        response:
          timeout: "25000"
        truststore:
          insecure: "true"
        client_id: "80c804bc5d854e4ba9cf50bd325d1f99"
        client_secret: "![wlrD0PJUqkg6a/Wrm/qo3iePGWxNULSRF5XXO4hgIcppGDRlN4ta6ElmpSfSuMRP]"
     
keystore:
  file:
    path: "keystore-nonproduction.jks"
  cert:
    alias: "mule"
  keypassword: "![O07aOQy/8wplLawz9ExPZw==]"
  storepassword: "![HjsP93B2e/Hl4iuv3sSUWQ==]"

autodiscovery:
  api: 
    id: "15732627"
  
anypoint:
  platform:
    client_id: "a82b5287c958457bab782867ca92fbf2"
    client_secret: "xxxxxxxxxxxxxxxxxxxx"
    base_uri: "https://anypoint.mulesoft.com"
    analytics_base_uri: "https://analytics-ingest.anypoint.mulesoft.com"